[build]
  command = "npm install --force && npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://api.binance.com/api/v3/ticker/24hr"
  REACT_APP_EXCHANGE_INFO_URL = "https://api.binance.com/api/v3/exchangeInfo"
  REACT_APP_KLINE_URL = "https://api.binance.com/api/v3/klines"
